### ISSUE TITLE
Why TR is set as ETH?

### ISSUE THREAD

**Issue by frankong** [ismrmrd/philips_to_ismrmrd#8]
The default xml file sets TR to be ETH. Is there a specific reason for that?

https://github.com/ismrmrd/philips_to_ismrmrd/blob/0e38eb07243a3f287d57b59431d5662605f9b969/IsmrmrdPhilips.xsl#L184-L186

**Comment by zwep** [comment]
Hi, I still have this error in my philips_to_ismrmrd version... and I tried and downloaded it last week. So why is this "bug" still there? 

I can edit this with Python of course... but that is not fixing the issue...

**Comment by dchansen** [comment]
The obvious answer is that no-one fixed it. 
Unfortunately we don't have any developers at Philips sites, making the Philips converter a "best effort" sort of project. As we also have don't have any support from Philips, everything has to be reverse engineered.
We would more than welcome help fixing/improving the Philips converter.

**Comment by zwep** [comment]
Ah thanks for the response!

I just started looking at the source code of the philips converterd and noticed that there was plenty of use of GPI. 

(After a Google search and some reading..)

They apparantly have function that can read lab/sin/raw files, but there are also functions to convert to ismrmrd format.  (See https://github.com/hansenms/gpi_ismrmrd/tree/master/ismrmrd/GPI)

So... if all that code works, and since this conversion is mostly based off of GPI's functionalities.. would you suggest to start using GPI instead? What would be the added benefit of this converter besides being a one-liner in a shell interface?
